//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalExamWCFclient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add", ReplyAction="http://tempuri.org/IService1/addResponse")]
        double add(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/add", ReplyAction="http://tempuri.org/IService1/addResponse")]
        System.Threading.Tasks.Task<double> addAsync(int a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculateTotalGuest", ReplyAction="http://tempuri.org/IService1/CalculateTotalGuestResponse")]
        int CalculateTotalGuest(int a, int b, int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculateTotalGuest", ReplyAction="http://tempuri.org/IService1/CalculateTotalGuestResponse")]
        System.Threading.Tasks.Task<int> CalculateTotalGuestAsync(int a, int b, int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GuestToString", ReplyAction="http://tempuri.org/IService1/GuestToStringResponse")]
        string GuestToString(int a, int b, int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GuestToString", ReplyAction="http://tempuri.org/IService1/GuestToStringResponse")]
        System.Threading.Tasks.Task<string> GuestToStringAsync(int a, int b, int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RoomToString", ReplyAction="http://tempuri.org/IService1/RoomToStringResponse")]
        string RoomToString(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RoomToString", ReplyAction="http://tempuri.org/IService1/RoomToStringResponse")]
        System.Threading.Tasks.Task<string> RoomToStringAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculateDiscount", ReplyAction="http://tempuri.org/IService1/CalculateDiscountResponse")]
        double CalculateDiscount(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculateDiscount", ReplyAction="http://tempuri.org/IService1/CalculateDiscountResponse")]
        System.Threading.Tasks.Task<double> CalculateDiscountAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculateRoomPrice", ReplyAction="http://tempuri.org/IService1/CalculateRoomPriceResponse")]
        double CalculateRoomPrice(int a, int b, double c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalculateRoomPrice", ReplyAction="http://tempuri.org/IService1/CalculateRoomPriceResponse")]
        System.Threading.Tasks.Task<double> CalculateRoomPriceAsync(int a, int b, double c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DisplayMsg", ReplyAction="http://tempuri.org/IService1/DisplayMsgResponse")]
        bool DisplayMsg(int a, int b, int c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DisplayMsg", ReplyAction="http://tempuri.org/IService1/DisplayMsgResponse")]
        System.Threading.Tasks.Task<bool> DisplayMsgAsync(int a, int b, int c);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : FinalExamWCFclient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<FinalExamWCFclient.ServiceReference1.IService1>, FinalExamWCFclient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double add(int a) {
            return base.Channel.add(a);
        }
        
        public System.Threading.Tasks.Task<double> addAsync(int a) {
            return base.Channel.addAsync(a);
        }
        
        public int CalculateTotalGuest(int a, int b, int c) {
            return base.Channel.CalculateTotalGuest(a, b, c);
        }
        
        public System.Threading.Tasks.Task<int> CalculateTotalGuestAsync(int a, int b, int c) {
            return base.Channel.CalculateTotalGuestAsync(a, b, c);
        }
        
        public string GuestToString(int a, int b, int c) {
            return base.Channel.GuestToString(a, b, c);
        }
        
        public System.Threading.Tasks.Task<string> GuestToStringAsync(int a, int b, int c) {
            return base.Channel.GuestToStringAsync(a, b, c);
        }
        
        public string RoomToString(int a, int b) {
            return base.Channel.RoomToString(a, b);
        }
        
        public System.Threading.Tasks.Task<string> RoomToStringAsync(int a, int b) {
            return base.Channel.RoomToStringAsync(a, b);
        }
        
        public double CalculateDiscount(int a, int b) {
            return base.Channel.CalculateDiscount(a, b);
        }
        
        public System.Threading.Tasks.Task<double> CalculateDiscountAsync(int a, int b) {
            return base.Channel.CalculateDiscountAsync(a, b);
        }
        
        public double CalculateRoomPrice(int a, int b, double c) {
            return base.Channel.CalculateRoomPrice(a, b, c);
        }
        
        public System.Threading.Tasks.Task<double> CalculateRoomPriceAsync(int a, int b, double c) {
            return base.Channel.CalculateRoomPriceAsync(a, b, c);
        }
        
        public bool DisplayMsg(int a, int b, int c) {
            return base.Channel.DisplayMsg(a, b, c);
        }
        
        public System.Threading.Tasks.Task<bool> DisplayMsgAsync(int a, int b, int c) {
            return base.Channel.DisplayMsgAsync(a, b, c);
        }
    }
}
